# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3179c16
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: ines.hamouni@epfl.ch
author_name: Inès Hamouni
github_org: InesHamouni
package_name: green_chemistry
project_name: Green-chemistry
short_description: This project is about green chemistry, mostly inspired by the 12 principles of green chemistry. Its purpose is to guide chemists with their reactants choice
                    while considering environmental impact and human health. 
                    This project is made as part of the Practical Programming in Chemistry course to gain experience with python programmation and explore github environment. 
